package com.luying.bean;

public class SysRoleResources {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resources.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resources.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resources.resources_id
     *
     * @mbggenerated
     */
    private Integer resourcesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resources.id
     *
     * @return the value of sys_role_resources.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resources.id
     *
     * @param id the value for sys_role_resources.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resources.role_id
     *
     * @return the value of sys_role_resources.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resources.role_id
     *
     * @param roleId the value for sys_role_resources.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resources.resources_id
     *
     * @return the value of sys_role_resources.resources_id
     *
     * @mbggenerated
     */
    public Integer getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resources.resources_id
     *
     * @param resourcesId the value for sys_role_resources.resources_id
     *
     * @mbggenerated
     */
    public void setResourcesId(Integer resourcesId) {
        this.resourcesId = resourcesId;
    }
}