package com.luying.dao;

import com.luying.bean.SysRoleResources;
import java.util.List;

public interface SysRoleResourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resources
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resources
     *
     * @mbggenerated
     */
    int insert(SysRoleResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resources
     *
     * @mbggenerated
     */
    SysRoleResources selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resources
     *
     * @mbggenerated
     */
    List<SysRoleResources> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resources
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRoleResources record);
}